#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title plant1 humidity
graph_vlabel humidity
plant1_hum.label humidity
plant1_hum.info Humidity level for plant1

EOM
        exit 0;;
esac

printf "plant1_hum.value "
cut -d',' -f2 /home/pi/plant_mon/plant1
